# our base image
FROM php:7.0-fpm


#install zip extension for composer
RUN apt-get update && apt-get install -y \
    zip \
    libgmp-dev \
    && pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install gmp

#install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data:www-data /var/www

WORKDIR  /var/www/php-node-client