# our base image
FROM php:7.1-fpm

RUN apt-get update
#install zip extension for composer
RUN apt-get install zip -y -q

#install composer(git needed)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data:www-data /var/www

WORKDIR  /var/www/php-node-client